# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-14 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fav_list',
            field=models.ManyToManyField(blank=True, related_name='liked_users', to='users.Product'),
        ),
    ]
